In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('녹색매장 지정 업체 및 매장현황 정보.csv', encoding='cp949')

In [3]:
df

      구분   지정번호      업체명      매장명                     지정기간
0     대형  제001호      이마트      성수점  2020-11-14 ~ 2023-11-13
1     대형  제002호      이마트      연수점  2020-11-14 ~ 2023-11-13
2     대형  제003호      이마트      고잔점  2020-11-14 ~ 2023-11-13
3     대형  제004호      이마트      산본점  2020-11-14 ~ 2023-11-13
4     대형  제013호  갤러리아백화점    타임월드점  2020-11-14 ~ 2023-11-13
..   ...    ...      ...      ...                      ...
426  중소형  제714호     초록마을    전주서신점  2021-09-01 ~ 2024-08-31
427  중소형  제715호  파라곤 홈마트      세종점  2021-09-01 ~ 2024-08-31
428  중소형  제716호     GS25  강남프리미엄점  2021-12-07 ~ 2024-12-06
429  중소형  제717호     GS25      건국점  2021-12-07 ~ 2024-12-06
430  중소형  제718호     GS25  동두천 송내점  2021-12-07 ~ 2024-12-06

[431 rows x 5 columns]

In [13]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

In [5]:
path = 'C:/Users/USER/Desktop/종민/Programs/chromedriver.exe'
driver = webdriver.Chrome(path)

In [6]:
driver.implicitly_wait(5)

In [22]:
driver.get('https://www.google.co.kr/maps/?hl=ko')

In [24]:
driver.find_element_by_css_selector('#searchboxinput').send_keys('이마트 성수점' + Keys.ENTER)

In [28]:
driver.find_element_by_css_selector('#QA0Szd > div > div > div.w6VYqd > div.bJzME.tTVLSc > div > div.e07Vkf.kA9KIf > div > div > div:nth-child(9) > div:nth-child(1) > button > div.AeaXub > div.rogA2c > div.Io6YTe.fontBodyMedium').text

'서울특별시 성동구 뚝섬로 379'

In [30]:
driver.find_element_by_css_selector('#searchbox > a').click()

In [31]:
driver.find_element_by_css_selector('#searchboxinput').send_keys('이마트 연수점' + Keys.ENTER)

In [32]:
driver.find_element_by_css_selector('#QA0Szd > div > div > div.w6VYqd > div.bJzME.tTVLSc > div > div.e07Vkf.kA9KIf > div > div > div:nth-child(9) > div:nth-child(1) > button > div.AeaXub > div.rogA2c > div.Io6YTe.fontBodyMedium').text

'인천광역시 연수구 동춘동 926-9'

In [38]:
driver.find_element_by_css_selector('#QA0Szd > div > div > div.w6VYqd > div.bJzME.tTVLSc > div > div.e07Vkf.kA9KIf > div > div > div.m6QErb.DxyBCb.kA9KIf.dS8AEf.ecceSd > div.m6QErb.DxyBCb.kA9KIf.dS8AEf.ecceSd > div:nth-child(3) > div > a').click()

In [40]:
driver.find_element_by_css_selector('#QA0Szd > div > div > div.w6VYqd > div.bJzME.Hu9e2e.tTVLSc > div > div.e07Vkf.kA9KIf > div > div > div.m6QErb.DxyBCb.kA9KIf.dS8AEf > div:nth-child(9) > div:nth-child(1) > button > div.AeaXub > div.rogA2c > div.Io6YTe.fontBodyMedium').text

'경기도 안산시 단원구 원포공원1로 46'

In [ ]:
for i in range(291, len(df)):
    name = df.loc[i, '업체명'] + ' ' + df.loc[i, '매장명']
    driver.find_element_by_css_selector('#searchbox > a').click()
    driver.find_element_by_css_selector('#searchboxinput').send_keys(name + Keys.ENTER)
    try:
        address = driver.find_element_by_css_selector('#QA0Szd > div > div > div.w6VYqd > div.bJzME.tTVLSc > div > div.e07Vkf.kA9KIf > div > div > div:nth-child(9) > div:nth-child(1) > button > div.AeaXub > div.rogA2c > div.Io6YTe.fontBodyMedium').text
    except:
        try:
            driver.find_element_by_css_selector('#QA0Szd > div > div > div.w6VYqd > div.bJzME.tTVLSc > div > div.e07Vkf.kA9KIf > div > div > div.m6QErb.DxyBCb.kA9KIf.dS8AEf.ecceSd > div.m6QErb.DxyBCb.kA9KIf.dS8AEf.ecceSd > div:nth-child(3) > div > a').click()
            address = driver.find_element_by_css_selector('#QA0Szd > div > div > div.w6VYqd > div.bJzME.Hu9e2e.tTVLSc > div > div.e07Vkf.kA9KIf > div > div > div.m6QErb.DxyBCb.kA9KIf.dS8AEf > div:nth-child(9) > div:nth-child(1) > button > div.AeaXub > div.rogA2c > div.Io6YTe.fontBodyMedium').text
        except:
            continue
    
    df.loc[i, '주소'] = address
    print(i, address)

In [149]:
df[df.주소.apply(lambda x : type(x) == str)].to_csv('address2.csv', index=False)

In [144]:
df.to_csv('address.csv', index=False)

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('address.csv')

In [3]:
df

,구분,지정번호,업체명,매장명,지정기간,주소
0,대형,제001호,이마트,성수점,2020-11-14 ~ 2023-11-13,서울특별시 성동구 뚝섬로 379
1,대형,제002호,이마트,연수점,2020-11-14 ~ 2023-11-13,인천광역시 연수구 동춘동 926-9
2,대형,제003호,이마트,고잔점,2020-11-14 ~ 2023-11-13,경기도 안산시 단원구 원포공원1로 46
3,대형,제004호,이마트,산본점,2020-11-14 ~ 2023-11-13,경기도 군포시 산본로 347
4,대형,제013호,갤러리아백화점,타임월드점,2020-11-14 ~ 2023-11-13,대전광역시 서구 둔산동 대덕대로 211
...,...,...,...,...,...,...
393,중소형,제712호,초록마을,나주빛가람중흥점,2021-09-01 ~ 2024-08-31,광주광역시 남구 행암동
394,중소형,제714호,초록마을,전주서신점,2021-09-01 ~ 2024-08-31,전라북도 전주시 완산구 효자동3가 1609-16
395,중소형,제716호,GS25,강남프리미엄점,2021-12-07 ~ 2024-12-06,서울특별시 강남구 역삼동 678-5 1층
396,중소형,제717호,GS25,건국점,2021-12-07 ~ 2024-12-06,서울특별시 광진구 화양동 500-3
397,중소형,제718호,GS25,동두천 송내점,2021-12-07 ~ 2024-12-06,경기도 동두천시 송내동 664-6

In [4]:
arr = '''37.5399389
37.4041584
37.3031255
37.3610506
36.352308
36.8004515
37.5284665
37.5578966
37.446547
37.2825088
37.4442613
37.517007
37.6003893
37.1231363
37.5040222
37.5708733
35.8533378
37.632646
37.650166
35.1270921
36.3439697
35.5380178
37.8809019
35.8545668
35.8163187
35.5760993
36.1137596
35.2114828
35.4127076
34.7771107
35.1967135
37.6549733
35.8711227
35.8708661
37.596438
37.3196884
37.2844549
37.3252976
37.2757153
36.1094691
37.4889386
37.2812183
37.3207268
37.5106681
37.5200705
37.5915475
37.6304816
37.5846917
37.507846
37.1494108
37.5667733
36.4268249
35.817143
37.5257763
37.5440476
37.3705055
37.5406924
37.4865038
37.6075197
37.6441006
37.4843751
37.6662792
37.3897387
36.3510151
37.5379063
37.5030493
37.5061119
37.372032
37.496158
37.3831046
37.3839118
37.2646595
36.8029915
37.2955753
37.5293136
37.4876872
37.6449369
37.5516256
37.649542
37.4773867
37.3963545
37.5032602
37.4883625
37.5103733
37.5307261
37.4912607
37.4440265
37.5406983
35.4315495
37.4897746
36.6204046
35.2395289
37.3374862
37.2527036
35.1329733
35.1443594
35.1659937
35.9827419
37.3983409
37.3031255
37.4629528
35.9301951
37.7088559
35.8851982
37.7469201
35.9920307
34.9572634
37.5621482
35.2266376
36.838181
36.8194099
37.7106854
37.5355702
37.3375066
37.4949074
37.5801191
37.5029698
37.3734611
37.3070387
37.4932114
36.3510151
37.5342626
37.6724029
35.2305899
37.4864085
37.0079613
35.8348664
37.60841
37.5070431
35.1761533
34.7579142
37.5376127
36.1359303
35.0134842
37.2653782
37.2833789
37.5134449
37.6733388
37.3363541
35.1940462
37.5149021
37.4936848
37.4774645
37.5160389
35.1823048
35.1625652
35.2135602
36.0602061
35.1602959
37.2981742
35.0848397
35.1930323
35.2026126
37.4589063
36.1379634
37.3895286
37.4991258
35.8224054
37.4773867
37.5516256
34.8655917
36.2863984
35.9657878
35.9664625
35.2026126
35.8342701
36.3200919
36.2944985
36.3486909
35.1390396
37.5888666

37.3042402
34.7659818
37.7351108
37.3946695
37.4021913
35.8340779
36.6440331
36.6322351
36.6685458
36.995646
35.1813055
36.7735212
35.9559394
37.1401046
35.2351734
35.1524663
37.4686493
37.5035125
37.5181712
37.251781
37.7521309
37.4975674
37.5379631
37.5394297
37.4516923
37.2037172

37.2700194
37.5677584
37.4004201
37.4649629
37.4845367
37.5318517
35.8406959
35.2346577
37.5589841
37.5516256
37.2509574
36.995646
37.3839118
34.96053
37.5120643
37.3055753
34.7457265
37.2851841
37.4517798
37.5085511
36.6322351
37.586332
35.1231379
35.2459204
37.3949611
35.83871
37.6123992
33.4824201
37.5716126
35.8544395
35.8544395
37.3839118
37.6716677
33.4901862
36.6677517
37.3057484
37.3289036
36.3843091
37.555042
37.6466623
33.2893347
38.207883
37.1830882
36.6371173
36.6365459
37.3458891
36.6260561
36.6268218
37.3271917
34.8911104
37.6432013
35.8606036
35.1794552
35.2226108
34.8059169
37.6648183
35.1742027
35.1495471
35.1643625
37.0449989
34.939919
37.5093957
37.3710995
37.6590106
35.8237098
35.806564
36.7871202
36.9901995
37.8242646
36.0127506
37.202769
36.1079026
36.3008798
37.3249213
37.5171482
37.7353974
36.367302
37.5041299
37.5609008
37.5609008
35.1788264
37.3126836
37.5961696
37.3450507
36.3556166
34.8409685
35.1747941
36.6192113
35.2229972
36.6307795
37.3456011
37.6329073
37.578048
37.5081687

36.6488779
36.6109051
36.6366609
36.6643529
36.6261122
36.2981922
36.3757158
33.5006475
33.4881257
33.492584
33.5197394
33.4823932
33.5168663
33.5168663
37.7556587
37.7215024
37.2627412
36.5873247
36.3439811
36.5548968
37.3337344
37.335769
35.0822777
37.5489656
37.2511575
37.6122886
37.2098027
37.5196089
35.1520351
37.3238887
37.4991258
37.5157197
37.3132491
37.501684
35.1545323
35.1468797
35.1781491
35.1219583

35.1597624
37.5363346
35.1480865
35.1897285
37.2307165
37.3218778
37.291873
37.3090307
37.471679
37.2854331
33.4896407
33.4906562
36.3016987
37.5792928
37.5049762
37.4722539
37.3171241
37.3805035
35.1581479
37.8685399
36.9055041
36.8262462
36.9883806
35.1523726
35.9645363
36.5988747
36.3499824
37.6043287
37.3332064
37.7940446
36.3432783
36.3432783
35.2158407
35.1783761
35.5347336
35.5123852
37.1409837
35.8690883
35.8601789
35.8628786
35.8601789
35.8215932
35.8666447
35.9351608
35.8450915
36.1604588
35.6872643
37.6018325
37.4936848
37.5468869
37.5361386
37.6149092
37.5029698
37.4273488
37.4774645
37.4753403
34.9537914
34.96053
37.3363541
35.145817
35.0991512
35.8273118
37.5028687
37.5450291
37.8872072'''

In [6]:
df['위도'] = arr.split('\n')

In [7]:
df

,구분,지정번호,업체명,매장명,지정기간,주소,위도
0,대형,제001호,이마트,성수점,2020-11-14 ~ 2023-11-13,서울특별시 성동구 뚝섬로 379,37.5399389
1,대형,제002호,이마트,연수점,2020-11-14 ~ 2023-11-13,인천광역시 연수구 동춘동 926-9,37.4041584
2,대형,제003호,이마트,고잔점,2020-11-14 ~ 2023-11-13,경기도 안산시 단원구 원포공원1로 46,37.3031255
3,대형,제004호,이마트,산본점,2020-11-14 ~ 2023-11-13,경기도 군포시 산본로 347,37.3610506
4,대형,제013호,갤러리아백화점,타임월드점,2020-11-14 ~ 2023-11-13,대전광역시 서구 둔산동 대덕대로 211,36.352308
...,...,...,...,...,...,...,...
393,중소형,제712호,초록마을,나주빛가람중흥점,2021-09-01 ~ 2024-08-31,광주광역시 남구 행암동,35.0991512
394,중소형,제714호,초록마을,전주서신점,2021-09-01 ~ 2024-08-31,전라북도 전주시 완산구 효자동3가 1609-16,35.8273118
395,중소형,제716호,GS25,강남프리미엄점,2021-12-07 ~ 2024-12-06,서울특별시 강남구 역삼동 678-5 1층,37.5028687
396,중소형,제717호,GS25,건국점,2021-12-07 ~ 2024-12-06,서울특별시 광진구 화양동 500-3,37.5450291
397,중소형,제718호,GS25,동두천 송내점,2021-12-07 ~ 2024-12-06,경기도 동두천시 송내동 664-6,37.8872072

In [10]:
arr = '''127.0531674
126.681106
126.812847
126.9314088
127.3785493
127.1046804
127.0400798
126.8622978
126.8844653
126.9701183
127.1413754
126.9041419
126.9202568
128.2228903
126.7639393
127.0213284
128.5101866
126.8333839
127.3093975
128.9685302
126.5888748
129.3483974
127.052276
127.120503
127.1025147
129.359324
128.3653763
129.0776055
129.1670202
127.6513144
128.0823743
127.2430664
128.6372145
128.7274592
127.0935903
127.0833256
127.6354062
127.1100001
127.0733398
128.3649177
127.0682415
127.1527193
127.1107704
127.0861994
127.0995
127.1393781
126.8315428
127.2144896
126.7320431
127.0730348
126.8025118
127.3869077
128.5236661
126.8703272
127.0148318
127.1057126
127.0946718
126.7815767
127.018009
126.667035
126.9723299
127.1133146
127.1017312
127.3978173
126.9475962
126.9956925
126.7084671
126.936118
126.998344
127.1254852
126.6438546
127.0412693
127.1192547
127.1277974
126.8751264
127.0174271
126.9275838
127.0257166
127.0763583
127.1285282
126.9488333
127.0100014
126.9937147
127.1262998
127.0352887
126.7531946
126.7976102
126.7360097
127.3837685
126.7233082
127.5161182
128.6556374
126.7304654
127.0716535
126.8755729
129.0642591
129.1673879
126.7348656
126.9352933
126.812847
127.0369582
126.9576491
127.1820536
128.5898126
126.751036
129.3980639
127.532626
127.0379421
128.6801916
127.1578183
127.1556344
126.7454839
126.8787085
127.116529
126.9522236
126.8831954
127.0104078
127.1202398
126.9857638
127.0567416
127.3978173
127.0712947
126.7573213
129.0098969
126.9472347
127.1995104
128.720196
127.1586827
126.8902185
129.081336
127.7150203
127.0726183
128.1178844
126.7119553
126.9959828
127.1017312
127.1041611
126.7553321
127.0916512
129.0670501
127.0475259
127.0507447
126.8687338
126.8625378
126.8722633
129.1799608
128.7069133
129.3738648
129.1465531
127.0460589
128.9715769
128.8013109
128.8076582
126.710533
128.4234923
126.9737526
127.0629873
128.544864
127.1285282
127.0257166
128.6861213
127.2388004
126.6993065
126.7194759
128.8076582
128.54889
127.3437897
127.3329295
127.3894906
129.1032457
127.0062903

127.047337
127.6599105
127.0630256
126.976568
126.7227887
127.1006955
127.4248313
127.5061104
127.4882501
127.1111928
128.5607439
126.4386374
126.9722179
128.2007689
129.01302
129.0273205
126.8968106
126.7550458
126.8959156
127.0725948
127.0710005
126.6706903
127.2125925
126.736176
126.7019408
127.0367495

127.0635891
126.8981147
126.725561
126.6706778
126.9565362
126.901043
128.7008673
129.0912292
126.9534616
127.0257166
127.0653738
127.1111928
126.6438546
127.5193909
127.0824157
127.0467413
127.6536361
127.4562443
126.7474522
126.6779131
127.5061104
126.9471435
129.0443787
129.0907176
127.1263741
128.6230423
126.9292744
126.4819325
126.9613687
128.6102694
128.6102694
126.6438546
126.7605095
126.5402105
127.4838287
126.8603132
126.7897818
127.3215537
126.9695336
127.0709672
126.2836308
128.5774827
128.4654162
127.4369183
127.4770312
126.8047331
127.4959216
127.4317494
126.8008523
128.616421
126.7897215
128.5635906
126.9304542
128.5857659
126.3996951
127.0435994
129.0931872
129.0648567
128.9780222
127.0595265
127.5087775
126.8877258
126.9509572
126.7688507
127.1500613
127.1140752
127.1205669
126.91638
127.1412717
129.348903
127.0684906
128.1895025
127.3354219
127.1081315
126.9055629
127.046992
127.3185032
127.0030692
126.9809889
126.9809889
129.1248781
126.8386017
127.0351896
126.8053095
127.4082375
128.410998
126.8767747
127.4967387
128.8695462
127.4175428
127.9274613
126.8311083
126.9691068
127.0036319

127.4650614
127.4837249
127.4410312
127.4887667
127.4665682
127.3788218
127.3163223
126.5188429
126.4968963
126.5428767
126.5701983
126.4830444
126.5256918
126.5256918
128.8986211
127.1887919
127.0301178
128.1904469
126.6135575
128.7551302
126.8125731
127.9649644
128.9782104
126.9134767
127.029557
127.0289749
127.0587938
126.9786988
126.8630202
127.078855
127.0629873
127.1322328
127.0784309
127.1088753
126.8478142
126.9100511
126.9011501
126.8797473

126.8803477
126.8811128
126.9329555
126.8269058
127.2102329
126.8308848
126.8387065
126.8586009
127.3109016
127.0599193
126.477452
126.5371244
127.3233076
127.0479007
126.7040634
126.4688958
126.8479131
126.9728853
128.6988018
127.7180797
126.6462036
127.1400882
127.11173
126.8523783
126.7164139
127.2993996
127.4503948
126.6592468
127.9622724
127.079448
127.3351479
127.3351479
129.0873066
129.1219704
129.2987032
129.4269413
127.0796619
128.6360577
128.635268
128.6222083
128.635268
128.5454915
128.6918387
128.5606006
129.1775965
128.4254338
127.9034145
126.9368041
127.0507447
126.8672611
126.8800227
126.9304818
127.0104078
126.9914147
126.8687338
126.8859359
127.5320216
127.5193909
127.0916512
126.7783542
126.8870136
127.1056437
127.0389781
127.0750251
127.0506172'''

In [11]:
df['경도'] = arr.split('\n')

In [12]:
df

,구분,지정번호,업체명,매장명,지정기간,주소,위도,경도
0,대형,제001호,이마트,성수점,2020-11-14 ~ 2023-11-13,서울특별시 성동구 뚝섬로 379,37.5399389,127.0531674
1,대형,제002호,이마트,연수점,2020-11-14 ~ 2023-11-13,인천광역시 연수구 동춘동 926-9,37.4041584,126.681106
2,대형,제003호,이마트,고잔점,2020-11-14 ~ 2023-11-13,경기도 안산시 단원구 원포공원1로 46,37.3031255,126.812847
3,대형,제004호,이마트,산본점,2020-11-14 ~ 2023-11-13,경기도 군포시 산본로 347,37.3610506,126.9314088
4,대형,제013호,갤러리아백화점,타임월드점,2020-11-14 ~ 2023-11-13,대전광역시 서구 둔산동 대덕대로 211,36.352308,127.3785493
...,...,...,...,...,...,...,...,...
393,중소형,제712호,초록마을,나주빛가람중흥점,2021-09-01 ~ 2024-08-31,광주광역시 남구 행암동,35.0991512,126.8870136
394,중소형,제714호,초록마을,전주서신점,2021-09-01 ~ 2024-08-31,전라북도 전주시 완산구 효자동3가 1609-16,35.8273118,127.1056437
395,중소형,제716호,GS25,강남프리미엄점,2021-12-07 ~ 2024-12-06,서울특별시 강남구 역삼동 678-5 1층,37.5028687,127.0389781
396,중소형,제717호,GS25,건국점,2021-12-07 ~ 2024-12-06,서울특별시 광진구 화양동 500-3,37.5450291,127.0750251
397,중소형,제718호,GS25,동두천 송내점,2021-12-07 ~ 2024-12-06,경기도 동두천시 송내동 664-6,37.8872072,127.0506172

In [23]:
df[df.위도.apply(bool)].to_csv('latlon.csv', index=False)